sudo: false

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'

install:
  - pip install --upgrade pip setuptools wheel
  - pip install --use-wheel -e .
  - pip install --use-wheel -e .[tests]

script:
  - py.test .
